const features = {
  // type: {type0: {name: "Human", dir: "human"}},
  // gender: {gender0: {name: "Male", dir: "male"}},
  // action: {
  //   action0: {name: "Blink", dir: "blink"},
  //   action1: {name: "Wink", dir: "wink"},
  // },
  bg: {
    bg0: { name: "Aqua", dir: "aqua" },
    bg1: { name: "Beach", dir: "beach1" },
    bg2: { name: "Blue", dir: "blue" },
    bg4: { name: "Desert", dir: "desert1" },
    bg6: { name: "Green", dir: "green" },
    bg7: { name: "Indigo", dir: "indigo" },
    bg8: { name: "Night", dir: "night1" },
    bg10: { name: "Ocean", dir: "ocean1" },
    bg12: { name: "Orange", dir: "orange" },
    bg13: { name: "Pink", dir: "pink" },
    bg14: { name: "Purple", dir: "purple" },
    bg15: { name: "Rainbow", dir: "rainbow1" },
    bg17: { name: "Red", dir: "red" },
    bg18: { name: "River", dir: "river1" },
    bg20: { name: "Space", dir: "space1" },
    bg22: { name: "Sunset", dir: "sunset1" },
    bg24: { name: "Winter", dir: "winter1" },
    bg26: { name: "Yellow", dir: "yellow" },
  },
  body: {
    body0: { name: "Black", dir: "black" },
    body1: { name: "Brown", dir: "brown" },
    // body2: { name: "Grey", dir: "grey" },
    body3: { name: "White", dir: "white" },
  },
  clothes: {
    clothes0: { name: "Baseball Jersey", dir: "baseball" },
    clothes1: { name: "Black Hoodie", dir: "black-hoodie" },
    clothes2: { name: "Black Puffy Coat", dir: "black-puffy-jacket" },
    clothes3: { name: "Black Logo Tee", dir: "black-tshirt" },
    clothes4: { name: "Striped Shirt", dir: "black-white-stripes" },
    clothes5: { name: "Prepy Blue Polo", dir: "blue-prepy" },
    clothes7: { name: "Blue Varsity Jacket", dir: "blue-varsity" },
    clothes8: { name: "Chef's Apron", dir: "chef" },
    clothes9: { name: "Christmas Sweater", dir: "christmas" },
    clothes10: { name: "Farmer's Overalls", dir: "farmer" },
    clothes11: { name: "Gold Tuxedo", dir: "gold-tuxedo" },
    clothes12: { name: "Gold Tee", dir: "gold" },
    clothes13: { name: "Green Jumpsuit", dir: "green-jumpsuit" },
    clothes15: { name: "Green Varsity Jacket", dir: "green-varsity" },
    clothes16: { name: "Grey Hoodie", dir: "grey-hoodie" },
    clothes17: { name: "Sporty Grey", dir: "grey-sport" },
    clothes18: { name: "Black Jumpsuit", dir: "jumpsuit" },
    clothes19: { name: "King's Robe", dir: "king" },
    clothes21: { name: "Rainbow Overalls", dir: "overall" },
    clothes22: { name: "Prepy Pink Polo", dir: "pink-prepy" },
    clothes23: { name: "Purple Tuxedo", dir: "purple-tuxedo" },
    clothes24: { name: "Lumberjack", dir: "red-plaid" },
    clothes25: { name: "Red Puffy Coat", dir: "red-puffy-jacket" },
    clothes26: { name: "Blue Robe", dir: "robe" },
    clothes27: { name: "Santa's Suit", dir: "santa" },
    clothes28: { name: "Shirtless", dir: "shirtless" },
    clothes29: { name: "Spa Robe", dir: "spa" },
    clothes30: { name: "Spacesuit", dir: "spacesuit" },
    clothes31: { name: "Suspenders", dir: "suspenders" },
    clothes32: { name: "Tank Top", dir: "tanktop" },
    clothes33: { name: "Tie Dye", dir: "tie-dye" },
    clothes34: { name: "Tie Only", dir: "tie" },
    clothes35: { name: "Greek Toga", dir: "toga" },
    clothes36: { name: "Classic Tuxedo", dir: "tuxedo" },
    clothes37: { name: "White Plaid", dir: "white-plaid" },
    clothes38: { name: "White Logo Tee", dir: "white-tshirt" },
  },
  eyebrows: {
    eyebrows0: { name: "Bold Black", dir: "black-bold" },
    eyebrows1: { name: "Down Black", dir: "black-down" },
    eyebrows2: { name: "Mad Black", dir: "black-mad" },
    eyebrows3: { name: "Sad Black", dir: "black-sad" },
    eyebrows4: { name: "Slitted Black", dir: "black-slit" },
    eyebrows5: { name: "Up Black", dir: "black-up" },
    eyebrows6: { name: "Bold Brown", dir: "brown-bold" },
    eyebrows7: { name: "Down Brown", dir: "brown-down" },
    eyebrows8: { name: "Mad Brown", dir: "brown-mad" },
    eyebrows9: { name: "Sad Brown", dir: "brown-sad" },
    eyebrows10: { name: "Slitted Brown", dir: "brown-slit" },
    eyebrows11: { name: "Up Brown", dir: "brown-up" },
    eyebrows12: { name: "Bold White", dir: "white-bold" },
    eyebrows13: { name: "Down White", dir: "white-down" },
    eyebrows14: { name: "Mad White", dir: "white-mad" },
    eyebrows15: { name: "Sad White", dir: "white-sad" },
    eyebrows16: { name: "Slitted White", dir: "white-slit" },
    eyebrows17: { name: "Up White", dir: "white-up" },
  },
  eyes: {
    eyes0: { name: "Crossed Brown", dir: "brown-crossed" },
    eyes1: { name: "Googly Brown", dir: "brown-googly" },
    eyes2: { name: "Sleepy Brown", dir: "brown-sleepy" },
    eyes3: { name: "Starry Brown", dir: "brown-starry" },
    eyes4: { name: "Winking Brown", dir: "brown-wink" },
    eyes5: { name: "Brown", dir: "brown" },
    eyes6: { name: "Crossed Dark Blue", dir: "darkblue-crossed" },
    eyes7: { name: "Googly Dark Blue", dir: "darkblue-googly" },
    eyes8: { name: "Sleepy Dark Blue", dir: "darkblue-sleepy" },
    eyes9: { name: "Starry Dark Blue", dir: "darkblue-starry" },
    eyes10: { name: "Winking Dark Blue", dir: "darkblue-wink" },
    eyes11: { name: "Dark Blue", dir: "darkblue" },
    eyes12: { name: "Crossed Green", dir: "green-crossed" },
    eyes13: { name: "Googly Green", dir: "green-googly" },
    eyes14: { name: "Sleepy Green", dir: "green-sleepy" },
    eyes15: { name: "Starry Green", dir: "green-starry" },
    eyes16: { name: "Winking Green", dir: "green-wink" },
    eyes17: { name: "Green", dir: "green" },
    eyes18: { name: "Crossed Grey", dir: "grey-crossed" },
    eyes19: { name: "Googly Grey", dir: "grey-googly" },
    eyes20: { name: "Sleepy Grey", dir: "grey-sleepy" },
    eyes21: { name: "Starry Grey", dir: "grey-starry" },
    eyes22: { name: "Winking Grey", dir: "grey-wink" },
    eyes23: { name: "Grey", dir: "grey" },
    eyes24: { name: "Crossed Light Blue", dir: "lightblue-crossed" },
    eyes25: { name: "Googly Light Blue", dir: "lightblue-googly" },
    eyes26: { name: "Sleepy Light Blue", dir: "lightblue-sleepy" },
    eyes27: { name: "Starry Light Blue", dir: "lightblue-starry" },
    eyes28: { name: "Winking Light Blue", dir: "lightblue-wink" },
    eyes29: { name: "Light Blue", dir: "lightblue" },
    eyes30: { name: "Crossed Red", dir: "red-crossed" },
    eyes31: { name: "Googly Red", dir: "red-googly" },
    eyes32: { name: "Sleepy Red", dir: "red-sleepy" },
    eyes33: { name: "Starry Red", dir: "red-starry" },
    eyes34: { name: "Winking Red", dir: "red-wink" },
    eyes35: { name: "Red", dir: "red" },
  },
  glasses: {
    glasses0: { name: "3D", dir: "3d" },
    glasses1: { name: "Bottom Gone", dir: "bottom-gone" },
    glasses3: { name: "Winter Goggles", dir: "goggles-snowboard" },
    glasses4: { name: "Pure Gold", dir: "gold" },
    glasses5: { name: "Hearts", dir: "heart" },
    glasses6: { name: "Fancy Monocle", dir: "monocle" },
    glasses7: { name: "Party Glasses", dir: "party" },
    glasses8: { name: "Retro Pair", dir: "retro" },
    glasses9: { name: "Tiny Pink Things", dir: "small" },
    glasses10: { name: "Space Glasses", dir: "space" },
    glasses11: { name: "Casual Sunglasses", dir: "sunglasses" },
  },
  hair: {
    hair1: { name: "Black Punk Spikes", dir: "black-punk" },
    hair2: { name: "Blond Bowl Cut", dir: "blond-bowl" },
    hair3: { name: "Blonde Buzz Cut", dir: "blond-buzz" },
    hair4: { name: "Blonde Middle Part", dir: "blond-curtain" },
    hair5: { name: "Messy Blonde", dir: "blond-messy" },
    hair6: { name: "Blonde Mohawk", dir: "blond-mohawk" },
    hair9: { name: "Short Blonde", dir: "blond-short" },
    hair10: { name: "Slick Back Blonde", dir: "blond-slick" },
    hair11: { name: "Spiky Blonde", dir: "blond-spiky" },
    hair12: { name: "Blonde", dir: "blond" },
    hair13: { name: "Blue Half Shave", dir: "blue-half-shave" },
    hair14: { name: "HUGE Afro", dir: "brown-afro-huge" },
    hair15: { name: "Afro", dir: "brown-afro" },
    hair16: { name: "Brown Bowl Cut", dir: "brown-bowl" },
    hair17: { name: "Brown Buzz Cut", dir: "brown-buzz" },
    hair18: { name: "Cornrows", dir: "brown-cornrow" },
    hair19: { name: "Brown Middle Part", dir: "brown-curtain" },
    hair20: { name: "High Top", dir: "brown-high-top" },
    hair21: { name: "Medium Top", dir: "brown-medium-top" },
    hair22: { name: "Short Top", dir: "brown-short-top" },
    hair23: { name: "Messy Brown", dir: "brown-messy" },
    hair24: { name: "Brown Mohawk", dir: "brown-mohawk" },
    hair27: { name: "Short Brown", dir: "brown-short" },
    hair28: { name: "Slick Back Brown", dir: "brown-slick" },
    hair29: { name: "Spiky Brown", dir: "brown-spiky" },
    hair30: { name: "Thin Buzz Cut", dir: "brown-thin" },
    hair31: { name: "Waves", dir: "brown-waves" },
    hair32: { name: "Brown", dir: "brown" },
    hair33: { name: "Dirty Blonde Bowl Cut", dir: "dirty-bowl" },
    hair34: { name: "Dirty Blonde Buzz Cut", dir: "dirty-buzz" },
    hair35: { name: "Dirty Blonde Middle Part", dir: "dirty-curtain" },
    hair36: { name: "Messy Dirty Blonde", dir: "dirty-messy" },
    hair37: { name: "Dirty Blonde Mohawk", dir: "dirty-mohawk" },
    hair40: { name: "Short Dirty Blonde", dir: "dirty-short" },
    hair41: { name: "Slick Back Dirty Blonde", dir: "dirty-slick" },
    hair42: { name: "Spiky Dirty Blonde", dir: "dirty-spiky" },
    hair43: { name: "Dirty Blonde", dir: "dirty" },
    hair44: { name: "Red Half Shave", dir: "red-half-shave" },
  },
  hat: {
    hat0: { name: "Baseball Cap", dir: "baseball" },
    hat1: { name: "Beanie", dir: "beanie" },
    hat3: { name: "Cake", dir: "cake" },
    hat4: { name: "Chef's Hat", dir: "chef" },
    hat5: { name: "Street Cone", dir: "cone" },
    hat6: { name: "Construction Hat", dir: "construction" },
    hat7: { name: "Cowboy Hat", dir: "cowboy" },
    hat8: { name: "Golden Crown", dir: "crown" },
    hat9: { name: "Elf Hat", dir: "elf" },
    hat10: { name: "Fireman's Hat", dir: "fireman" },
    hat11: { name: "Football Helmet", dir: "football" },
    hat12: { name: "Golden Hat", dir: "gold" },
    hat13: { name: "Halo", dir: "halo" },
    hat14: { name: "Helicopter Hat", dir: "helicopter" },
    hat16: { name: "Leprechaun", dir: "leprechaun" },
    hat17: { name: "The Logo Hat", dir: "logo" },
    hat18: { name: "Party Hat", dir: "party" },
    hat19: { name: "Purple Pom Pom", dir: "purple-pom-pom" },
    hat20: { name: "Santa's Hat", dir: "santa" },
    hat22: { name: "Dizzy Stars", dir: "stars" },
  },
  head: {
    head0: { name: "Big Black", dir: "black-big" },
    head1: { name: "Pointy Black", dir: "black-point" },
    head2: { name: "Round Black", dir: "black-round" },
    head3: { name: "Big Brown", dir: "brown-big" },
    head4: { name: "Pointy Brown", dir: "brown-point" },
    head5: { name: "Round Brown", dir: "brown-round" },
    head6: { name: "Big White", dir: "white-big" },
    head7: { name: "Pointy White", dir: "white-point" },
    head8: { name: "Round White", dir: "white-round" },
    // head9: { name: "Big Grey", dir: "grey-big" },
    // head10: { name: "Point Grey", dir: "grey-point" },
    // head11: { name: "Round Grey", dir: "grey-round" },
  },
  jewelry: {
    earrings0: { name: "Big Diamond", dir: "diamond-big-earrings" },
    earrings1: { name: "Diamond", dir: "diamond-earrings" },
    earrings2: { name: "Big Gold", dir: "gold-big-earrings" },
    earrings3: { name: "Gold", dir: "gold-earrings" },
    earrings4: { name: "Golden Loop", dir: "gold-loop-earrings" },
    jewelry0: { name: "Big Diamond Chain", dir: "diamond-big-chain" },
    jewelry1: { name: "Diamond Chain", dir: "diamond-chain" },
    jewelry2: { name: "Diamond Cuban Link", dir: "diamond-cuban-link" },
    jewelry3: { name: "Diamond V Shape Chain", dir: "diamond-v-chain" },
    jewelry4: { name: "Big Gold Chain", dir: "gold-big-chain" },
    jewelry5: { name: "Gold Chain", dir: "gold-chain" },
    jewelry6: { name: "Gold Cuban Link", dir: "gold-cuban-link" },
    jewelry7: { name: "Gold V Shape Chain", dir: "gold-v-chain" },
  },
  mouth: {
    mouth0: { name: "Frown Black", dir: "black-frown" },
    mouth1: { name: "Grin Black", dir: "black-grin" },
    mouth2: { name: "Happy Black", dir: "black-happy" },
    mouth3: { name: "Smirk Black", dir: "black-smirk" },
    mouth4: { name: "Tongue Black", dir: "black-tongue" },
    mouth5: { name: "Normal Black", dir: "black" },
    mouth6: { name: "Frown Brown", dir: "brown-frown" },
    mouth7: { name: "Grin Brown", dir: "brown-grin" },
    mouth8: { name: "Happy Brown", dir: "brown-happy" },
    mouth9: { name: "Smirk Brown", dir: "brown-smirk" },
    mouth10: { name: "Tongue Brown", dir: "brown-tongue" },
    mouth11: { name: "Normal Brown", dir: "brown" },
    mouth12: { name: "Frown White", dir: "white-frown" },
    mouth13: { name: "Grin White", dir: "white-grin" },
    mouth14: { name: "Happy White", dir: "white-happy" },
    mouth15: { name: "Smirk White", dir: "white-smirk" },
    mouth16: { name: "Tongue White", dir: "white-tongue" },
    mouth17: { name: "Normal White", dir: "white" },
    mouth18: { name: "Buck Teeth", dir: "buck-tooth" },
    mouth19: { name: "Drool", dir: "drool" },
    mouth20: { name: "Gold Teeth", dir: "gold-smile" },
    mouth21: { name: "Missing Tooth", dir: "missing-tooth" },
    mouth22: { name: "One Tooth", dir: "one-tooth" },
    mouth23: { name: "Open", dir: "open" },
    mouth24: { name: "Shocked", dir: "shocked" },
    mouth25: { name: "Smile", dir: "smile" },
    mouth26: { name: "Upper Teeth", dir: "upper-smile" },
  },
  nose: {
    nose0: { name: "Big Black", dir: "black-big" },
    nose1: { name: "Hook Black", dir: "black-hook" },
    nose2: { name: "Long Black", dir: "black-long" },
    nose3: { name: "Normal Black", dir: "black" },
    nose4: { name: "Big Brown", dir: "brown-big" },
    nose5: { name: "Hook Brown", dir: "brown-hook" },
    nose6: { name: "Long Brown", dir: "brown-long" },
    nose7: { name: "Normal Brown", dir: "brown" },
    nose8: { name: "Big White", dir: "white-big" },
    nose9: { name: "Hook White", dir: "white-hook" },
    nose10: { name: "Long White", dir: "white-long" },
    nose11: { name: "Normal White", dir: "white" },
  },
  // smile: {
  //   smile0: {name: "Gold Teeth", dir: "gold-smile"},
  //   smile1: {name: "Missing Tooth", dir: "missing-tooth"},
  //   smile2: {name: "Smile", dir: "smile"},
  //   smile3: {name: "One Tooth", dir: "one-tooth"},
  //   smile4: {name: "Upper Teeth", dir: "upper-smile"},
  // },
};

module.exports = {
  features,
};
